/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedLayoutImport } from './routes/_protected/layout'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as authVerifyEmailImport } from './routes/(auth)/verify-email'
import { Route as authVerificationSentImport } from './routes/(auth)/verification-sent'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as ProtectedphysicalAssetStocksImport } from './routes/_protected/(physical-asset)/stocks'
import { Route as ProtectedphysicalAssetPeripheralsImport } from './routes/_protected/(physical-asset)/peripherals'
import { Route as ProtectedfinanceSalesImport } from './routes/_protected/(finance)/sales'
import { Route as ProtectedfinancePurchasesImport } from './routes/_protected/(finance)/purchases'
import { Route as ProtectedfinancePaymentMethodsImport } from './routes/_protected/(finance)/payment-methods'
import { Route as ProtectedfinanceAccountsImport } from './routes/_protected/(finance)/accounts'
import { Route as ProtectedclinicTreatmentsImport } from './routes/_protected/(clinic)/treatments'
import { Route as ProtectedclinicStaffListImport } from './routes/_protected/(clinic)/staff-list'
import { Route as ProtectedclinicReservationsImport } from './routes/_protected/(clinic)/reservations'
import { Route as ProtectedclinicPatientsImport } from './routes/_protected/(clinic)/patients'
import { Route as ProtectedclinicStaffStaffIdImport } from './routes/_protected/(clinic)/staff.$staffId'

// Create/Update Routes

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const authVerifyEmailRoute = authVerifyEmailImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRoute,
} as any)

const authVerificationSentRoute = authVerificationSentImport.update({
  id: '/(auth)/verification-sent',
  path: '/verification-sent',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedphysicalAssetStocksRoute =
  ProtectedphysicalAssetStocksImport.update({
    id: '/(physical-asset)/stocks',
    path: '/stocks',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedphysicalAssetPeripheralsRoute =
  ProtectedphysicalAssetPeripheralsImport.update({
    id: '/(physical-asset)/peripherals',
    path: '/peripherals',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedfinanceSalesRoute = ProtectedfinanceSalesImport.update({
  id: '/(finance)/sales',
  path: '/sales',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedfinancePurchasesRoute = ProtectedfinancePurchasesImport.update({
  id: '/(finance)/purchases',
  path: '/purchases',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedfinancePaymentMethodsRoute =
  ProtectedfinancePaymentMethodsImport.update({
    id: '/(finance)/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedfinanceAccountsRoute = ProtectedfinanceAccountsImport.update({
  id: '/(finance)/accounts',
  path: '/accounts',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedclinicTreatmentsRoute = ProtectedclinicTreatmentsImport.update({
  id: '/(clinic)/treatments',
  path: '/treatments',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedclinicStaffListRoute = ProtectedclinicStaffListImport.update({
  id: '/(clinic)/staff-list',
  path: '/staff-list',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedclinicReservationsRoute =
  ProtectedclinicReservationsImport.update({
    id: '/(clinic)/reservations',
    path: '/reservations',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedclinicPatientsRoute = ProtectedclinicPatientsImport.update({
  id: '/(clinic)/patients',
  path: '/patients',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedclinicStaffStaffIdRoute =
  ProtectedclinicStaffStaffIdImport.update({
    id: '/(clinic)/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/verification-sent': {
      id: '/(auth)/verification-sent'
      path: '/verification-sent'
      fullPath: '/verification-sent'
      preLoaderRoute: typeof authVerificationSentImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(clinic)/patients': {
      id: '/_protected/(clinic)/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ProtectedclinicPatientsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(clinic)/reservations': {
      id: '/_protected/(clinic)/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ProtectedclinicReservationsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(clinic)/staff-list': {
      id: '/_protected/(clinic)/staff-list'
      path: '/staff-list'
      fullPath: '/staff-list'
      preLoaderRoute: typeof ProtectedclinicStaffListImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(clinic)/treatments': {
      id: '/_protected/(clinic)/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof ProtectedclinicTreatmentsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(finance)/accounts': {
      id: '/_protected/(finance)/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedfinanceAccountsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(finance)/payment-methods': {
      id: '/_protected/(finance)/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof ProtectedfinancePaymentMethodsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(finance)/purchases': {
      id: '/_protected/(finance)/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof ProtectedfinancePurchasesImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(finance)/sales': {
      id: '/_protected/(finance)/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof ProtectedfinanceSalesImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(physical-asset)/peripherals': {
      id: '/_protected/(physical-asset)/peripherals'
      path: '/peripherals'
      fullPath: '/peripherals'
      preLoaderRoute: typeof ProtectedphysicalAssetPeripheralsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(physical-asset)/stocks': {
      id: '/_protected/(physical-asset)/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof ProtectedphysicalAssetStocksImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/(clinic)/staff/$staffId': {
      id: '/_protected/(clinic)/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof ProtectedclinicStaffStaffIdImport
      parentRoute: typeof ProtectedLayoutImport
    }
  }
}

// Create and export the route tree

interface ProtectedLayoutRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedclinicPatientsRoute: typeof ProtectedclinicPatientsRoute
  ProtectedclinicReservationsRoute: typeof ProtectedclinicReservationsRoute
  ProtectedclinicStaffListRoute: typeof ProtectedclinicStaffListRoute
  ProtectedclinicTreatmentsRoute: typeof ProtectedclinicTreatmentsRoute
  ProtectedfinanceAccountsRoute: typeof ProtectedfinanceAccountsRoute
  ProtectedfinancePaymentMethodsRoute: typeof ProtectedfinancePaymentMethodsRoute
  ProtectedfinancePurchasesRoute: typeof ProtectedfinancePurchasesRoute
  ProtectedfinanceSalesRoute: typeof ProtectedfinanceSalesRoute
  ProtectedphysicalAssetPeripheralsRoute: typeof ProtectedphysicalAssetPeripheralsRoute
  ProtectedphysicalAssetStocksRoute: typeof ProtectedphysicalAssetStocksRoute
  ProtectedclinicStaffStaffIdRoute: typeof ProtectedclinicStaffStaffIdRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedclinicPatientsRoute: ProtectedclinicPatientsRoute,
  ProtectedclinicReservationsRoute: ProtectedclinicReservationsRoute,
  ProtectedclinicStaffListRoute: ProtectedclinicStaffListRoute,
  ProtectedclinicTreatmentsRoute: ProtectedclinicTreatmentsRoute,
  ProtectedfinanceAccountsRoute: ProtectedfinanceAccountsRoute,
  ProtectedfinancePaymentMethodsRoute: ProtectedfinancePaymentMethodsRoute,
  ProtectedfinancePurchasesRoute: ProtectedfinancePurchasesRoute,
  ProtectedfinanceSalesRoute: ProtectedfinanceSalesRoute,
  ProtectedphysicalAssetPeripheralsRoute:
    ProtectedphysicalAssetPeripheralsRoute,
  ProtectedphysicalAssetStocksRoute: ProtectedphysicalAssetStocksRoute,
  ProtectedclinicStaffStaffIdRoute: ProtectedclinicStaffStaffIdRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verification-sent': typeof authVerificationSentRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/patients': typeof ProtectedclinicPatientsRoute
  '/reservations': typeof ProtectedclinicReservationsRoute
  '/staff-list': typeof ProtectedclinicStaffListRoute
  '/treatments': typeof ProtectedclinicTreatmentsRoute
  '/accounts': typeof ProtectedfinanceAccountsRoute
  '/payment-methods': typeof ProtectedfinancePaymentMethodsRoute
  '/purchases': typeof ProtectedfinancePurchasesRoute
  '/sales': typeof ProtectedfinanceSalesRoute
  '/peripherals': typeof ProtectedphysicalAssetPeripheralsRoute
  '/stocks': typeof ProtectedphysicalAssetStocksRoute
  '/staff/$staffId': typeof ProtectedclinicStaffStaffIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verification-sent': typeof authVerificationSentRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/patients': typeof ProtectedclinicPatientsRoute
  '/reservations': typeof ProtectedclinicReservationsRoute
  '/staff-list': typeof ProtectedclinicStaffListRoute
  '/treatments': typeof ProtectedclinicTreatmentsRoute
  '/accounts': typeof ProtectedfinanceAccountsRoute
  '/payment-methods': typeof ProtectedfinancePaymentMethodsRoute
  '/purchases': typeof ProtectedfinancePurchasesRoute
  '/sales': typeof ProtectedfinanceSalesRoute
  '/peripherals': typeof ProtectedphysicalAssetPeripheralsRoute
  '/stocks': typeof ProtectedphysicalAssetStocksRoute
  '/staff/$staffId': typeof ProtectedclinicStaffStaffIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verification-sent': typeof authVerificationSentRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/(clinic)/patients': typeof ProtectedclinicPatientsRoute
  '/_protected/(clinic)/reservations': typeof ProtectedclinicReservationsRoute
  '/_protected/(clinic)/staff-list': typeof ProtectedclinicStaffListRoute
  '/_protected/(clinic)/treatments': typeof ProtectedclinicTreatmentsRoute
  '/_protected/(finance)/accounts': typeof ProtectedfinanceAccountsRoute
  '/_protected/(finance)/payment-methods': typeof ProtectedfinancePaymentMethodsRoute
  '/_protected/(finance)/purchases': typeof ProtectedfinancePurchasesRoute
  '/_protected/(finance)/sales': typeof ProtectedfinanceSalesRoute
  '/_protected/(physical-asset)/peripherals': typeof ProtectedphysicalAssetPeripheralsRoute
  '/_protected/(physical-asset)/stocks': typeof ProtectedphysicalAssetStocksRoute
  '/_protected/(clinic)/staff/$staffId': typeof ProtectedclinicStaffStaffIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verification-sent'
    | '/verify-email'
    | '/dashboard'
    | '/patients'
    | '/reservations'
    | '/staff-list'
    | '/treatments'
    | '/accounts'
    | '/payment-methods'
    | '/purchases'
    | '/sales'
    | '/peripherals'
    | '/stocks'
    | '/staff/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verification-sent'
    | '/verify-email'
    | '/dashboard'
    | '/patients'
    | '/reservations'
    | '/staff-list'
    | '/treatments'
    | '/accounts'
    | '/payment-methods'
    | '/purchases'
    | '/sales'
    | '/peripherals'
    | '/stocks'
    | '/staff/$staffId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verification-sent'
    | '/(auth)/verify-email'
    | '/_protected/dashboard'
    | '/_protected/(clinic)/patients'
    | '/_protected/(clinic)/reservations'
    | '/_protected/(clinic)/staff-list'
    | '/_protected/(clinic)/treatments'
    | '/_protected/(finance)/accounts'
    | '/_protected/(finance)/payment-methods'
    | '/_protected/(finance)/purchases'
    | '/_protected/(finance)/sales'
    | '/_protected/(physical-asset)/peripherals'
    | '/_protected/(physical-asset)/stocks'
    | '/_protected/(clinic)/staff/$staffId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerificationSentRoute: typeof authVerificationSentRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerificationSentRoute: authVerificationSentRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/register",
        "/(auth)/reset-password",
        "/(auth)/verification-sent",
        "/(auth)/verify-email"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected/layout.tsx",
      "children": [
        "/_protected/dashboard",
        "/_protected/(clinic)/patients",
        "/_protected/(clinic)/reservations",
        "/_protected/(clinic)/staff-list",
        "/_protected/(clinic)/treatments",
        "/_protected/(finance)/accounts",
        "/_protected/(finance)/payment-methods",
        "/_protected/(finance)/purchases",
        "/_protected/(finance)/sales",
        "/_protected/(physical-asset)/peripherals",
        "/_protected/(physical-asset)/stocks",
        "/_protected/(clinic)/staff/$staffId"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx"
    },
    "/(auth)/verification-sent": {
      "filePath": "(auth)/verification-sent.tsx"
    },
    "/(auth)/verify-email": {
      "filePath": "(auth)/verify-email.tsx"
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx",
      "parent": "/_protected"
    },
    "/_protected/(clinic)/patients": {
      "filePath": "_protected/(clinic)/patients.tsx",
      "parent": "/_protected"
    },
    "/_protected/(clinic)/reservations": {
      "filePath": "_protected/(clinic)/reservations.tsx",
      "parent": "/_protected"
    },
    "/_protected/(clinic)/staff-list": {
      "filePath": "_protected/(clinic)/staff-list.tsx",
      "parent": "/_protected"
    },
    "/_protected/(clinic)/treatments": {
      "filePath": "_protected/(clinic)/treatments.tsx",
      "parent": "/_protected"
    },
    "/_protected/(finance)/accounts": {
      "filePath": "_protected/(finance)/accounts.tsx",
      "parent": "/_protected"
    },
    "/_protected/(finance)/payment-methods": {
      "filePath": "_protected/(finance)/payment-methods.tsx",
      "parent": "/_protected"
    },
    "/_protected/(finance)/purchases": {
      "filePath": "_protected/(finance)/purchases.tsx",
      "parent": "/_protected"
    },
    "/_protected/(finance)/sales": {
      "filePath": "_protected/(finance)/sales.tsx",
      "parent": "/_protected"
    },
    "/_protected/(physical-asset)/peripherals": {
      "filePath": "_protected/(physical-asset)/peripherals.tsx",
      "parent": "/_protected"
    },
    "/_protected/(physical-asset)/stocks": {
      "filePath": "_protected/(physical-asset)/stocks.tsx",
      "parent": "/_protected"
    },
    "/_protected/(clinic)/staff/$staffId": {
      "filePath": "_protected/(clinic)/staff.$staffId.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
