import type { Doctor, Reservation } from './types';

export const mockDoctors: Doctor[] = [
  {
    id: '1',
    firstName: 'Soap',
    lastName: 'Mactavish',
    position: 'Dentist',
    todayAppointments: 4,
    isAvailable: true,
  },
  {
    id: '2',
    firstName: 'Jerald',
    lastName: "O'Hara",
    position: 'Dentist',
    todayAppointments: 1,
    isAvailable: true,
  },
  {
    id: '3',
    firstName: 'Putri',
    lastName: 'Larasati',
    position: 'Dentist',
    todayAppointments: 0,
    isAvailable: false,
  },
  {
    id: '4',
    firstName: 'Simon',
    lastName: 'Riley',
    position: 'Orthodontist',
    todayAppointments: 3,
    isAvailable: true,
  },
  {
    id: '5',
    firstName: 'John',
    lastName: 'Price',
    position: 'Oral Surgeon',
    todayAppointments: 2,
    isAvailable: true,
  },
  {
    id: '6',
    firstName: 'Kyle',
    lastName: 'Garrick',
    position: 'Dentist',
    todayAppointments: 5,
    isAvailable: true,
  },
  {
    id: '7',
    firstName: 'Alex',
    lastName: 'Mason',
    position: 'Endodontist',
    todayAppointments: 2,
    isAvailable: true,
  },
  {
    id: '8',
    firstName: 'Frank',
    lastName: 'Woods',
    position: 'Periodontist',
    todayAppointments: 0,
    isAvailable: false,
  },
  {
    id: '9',
    firstName: 'Helen',
    lastName: 'Park',
    position: 'Dentist',
    todayAppointments: 4,
    isAvailable: true,
  },
  {
    id: '10',
    firstName: 'Samantha',
    lastName: 'Maxis',
    position: 'Pediatric Dentist',
    todayAppointments: 3,
    isAvailable: true,
  },
  {
    id: '11',
    firstName: 'Russell',
    lastName: 'Adler',
    position: 'Prosthodontist',
    todayAppointments: 1,
    isAvailable: true,
  },
  {
    id: '12',
    firstName: 'Lazar',
    lastName: 'Azoulay',
    position: 'Dentist',
    todayAppointments: 2,
    isAvailable: true,
  },
  {
    id: '13',
    firstName: 'Jessica',
    lastName: 'Stone',
    position: 'Oral Surgeon',
    todayAppointments: 0,
    isAvailable: false,
  },
];

const today = new Date();
today.setHours(0, 0, 0, 0);

const createDate = (hour: number, minute = 0) => {
  const date = new Date(today);
  date.setHours(hour, minute, 0, 0);
  return date;
};

export const mockReservations: Reservation[] = [
  {
    id: '1',
    startTime: createDate(9, 0),
    endTime: createDate(10, 0),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[0],
    patient: { id: 'p1', name: 'Rafli Jainudin' },
    treatment: { id: 't1', name: 'General Checkup' },
  },
  {
    id: '2',
    startTime: createDate(10, 0),
    endTime: createDate(11, 0),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[0],
    patient: { id: 'p2', name: 'Sekar Nandita' },
    treatment: { id: 't2', name: 'Scaling' },
  },
  {
    id: '3',
    startTime: createDate(12, 0),
    endTime: createDate(13, 0),
    duration: 60,
    status: 'ENCOUNTER',
    doctor: mockDoctors[0],
    patient: { id: 'p3', name: 'Lembayung Senja' },
    treatment: { id: 't3', name: 'Extraction' },
  },
  {
    id: '4',
    startTime: createDate(14, 30),
    endTime: createDate(15, 30),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[0],
    patient: { id: 'p4', name: 'Daniswara' },
    treatment: { id: 't4', name: 'General Checkup' },
  },
  {
    id: '5',
    startTime: createDate(11, 0),
    endTime: createDate(12, 0),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[1],
    patient: { id: 'p5', name: 'Angkasa Pura' },
    treatment: { id: 't5', name: 'Bleaching' },
  },
  {
    id: '6',
    startTime: createDate(14, 30),
    endTime: createDate(15, 30),
    duration: 60,
    status: 'PENDING',
    note: 'WAITING PAYMENT',
    doctor: mockDoctors[1],
    patient: { id: 'p6', name: 'Raihan' },
    treatment: { id: 't6', name: 'Filling' },
  },
  // Doctor 4 - Simon Riley
  {
    id: '7',
    startTime: createDate(8, 0),
    endTime: createDate(9, 30),
    duration: 90,
    status: 'DONE',
    doctor: mockDoctors[3],
    patient: { id: 'p7', name: 'Ahmad Rizky' },
    treatment: { id: 't7', name: 'Braces Adjustment' },
  },
  {
    id: '8',
    startTime: createDate(10, 0),
    endTime: createDate(11, 0),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[3],
    patient: { id: 'p8', name: 'Maya Putri' },
    treatment: { id: 't8', name: 'Retainer Check' },
  },
  {
    id: '9',
    startTime: createDate(14, 0),
    endTime: createDate(15, 0),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[3],
    patient: { id: 'p9', name: 'Budi Santoso' },
    treatment: { id: 't9', name: 'Orthodontic Consultation' },
  },
  // Doctor 5 - John Price
  {
    id: '10',
    startTime: createDate(7, 0),
    endTime: createDate(8, 30),
    duration: 90,
    status: 'DONE',
    doctor: mockDoctors[4],
    patient: { id: 'p10', name: 'Dewi Lestari' },
    treatment: { id: 't10', name: 'Wisdom Tooth Extraction' },
  },
  {
    id: '11',
    startTime: createDate(9, 0),
    endTime: createDate(10, 30),
    duration: 90,
    status: 'ENCOUNTER',
    doctor: mockDoctors[4],
    patient: { id: 'p11', name: 'Eko Prasetyo' },
    treatment: { id: 't11', name: 'Dental Implant' },
  },
  // Doctor 6 - Kyle Garrick
  {
    id: '12',
    startTime: createDate(6, 30),
    endTime: createDate(7, 30),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[5],
    patient: { id: 'p12', name: 'Fitria Rahmawati' },
    treatment: { id: 't12', name: 'Early Checkup' },
  },
  {
    id: '13',
    startTime: createDate(8, 0),
    endTime: createDate(9, 0),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[5],
    patient: { id: 'p13', name: 'Galih Permana' },
    treatment: { id: 't13', name: 'Cleaning' },
  },
  {
    id: '14',
    startTime: createDate(10, 0),
    endTime: createDate(11, 0),
    duration: 60,
    status: 'ENCOUNTER',
    doctor: mockDoctors[5],
    patient: { id: 'p14', name: 'Hana Safira' },
    treatment: { id: 't14', name: 'Filling' },
  },
  {
    id: '15',
    startTime: createDate(11, 30),
    endTime: createDate(12, 30),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[5],
    patient: { id: 'p15', name: 'Irfan Hakim' },
    treatment: { id: 't15', name: 'Root Canal' },
  },
  {
    id: '16',
    startTime: createDate(15, 0),
    endTime: createDate(16, 0),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[5],
    patient: { id: 'p16', name: 'Joko Widodo' },
    treatment: { id: 't16', name: 'Crown Fitting' },
  },
  // Doctor 7 - Alex Mason
  {
    id: '17',
    startTime: createDate(9, 0),
    endTime: createDate(10, 30),
    duration: 90,
    status: 'DONE',
    doctor: mockDoctors[6],
    patient: { id: 'p17', name: 'Kartika Sari' },
    treatment: { id: 't17', name: 'Root Canal Treatment' },
  },
  {
    id: '18',
    startTime: createDate(14, 0),
    endTime: createDate(15, 30),
    duration: 90,
    status: 'PENDING',
    doctor: mockDoctors[6],
    patient: { id: 'p18', name: 'Lukman Hakim' },
    treatment: { id: 't18', name: 'Pulp Therapy' },
  },
  // Doctor 9 - Helen Park
  {
    id: '19',
    startTime: createDate(7, 30),
    endTime: createDate(8, 30),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[8],
    patient: { id: 'p19', name: 'Mega Wati' },
    treatment: { id: 't19', name: 'Morning Checkup' },
  },
  {
    id: '20',
    startTime: createDate(9, 0),
    endTime: createDate(10, 0),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[8],
    patient: { id: 'p20', name: 'Nadia Putri' },
    treatment: { id: 't20', name: 'Scaling' },
  },
  {
    id: '21',
    startTime: createDate(11, 0),
    endTime: createDate(12, 0),
    duration: 60,
    status: 'ENCOUNTER',
    doctor: mockDoctors[8],
    patient: { id: 'p21', name: 'Oscar Tan' },
    treatment: { id: 't21', name: 'Whitening' },
  },
  {
    id: '22',
    startTime: createDate(16, 0),
    endTime: createDate(17, 0),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[8],
    patient: { id: 'p22', name: 'Putri Ayu' },
    treatment: { id: 't22', name: 'Evening Checkup' },
  },
  // Doctor 10 - Samantha Maxis
  {
    id: '23',
    startTime: createDate(8, 0),
    endTime: createDate(8, 45),
    duration: 45,
    status: 'DONE',
    doctor: mockDoctors[9],
    patient: { id: 'p23', name: 'Qiana (child)' },
    treatment: { id: 't23', name: 'Pediatric Checkup' },
  },
  {
    id: '24',
    startTime: createDate(9, 0),
    endTime: createDate(9, 45),
    duration: 45,
    status: 'DONE',
    doctor: mockDoctors[9],
    patient: { id: 'p24', name: 'Rafi (child)' },
    treatment: { id: 't24', name: 'Fluoride Treatment' },
  },
  {
    id: '25',
    startTime: createDate(10, 0),
    endTime: createDate(10, 45),
    duration: 45,
    status: 'ENCOUNTER',
    doctor: mockDoctors[9],
    patient: { id: 'p25', name: 'Sinta (child)' },
    treatment: { id: 't25', name: 'Cavity Filling' },
  },
  // Doctor 11 - Russell Adler
  {
    id: '26',
    startTime: createDate(10, 0),
    endTime: createDate(11, 30),
    duration: 90,
    status: 'PENDING',
    doctor: mockDoctors[10],
    patient: { id: 'p26', name: 'Tono Sucipto' },
    treatment: { id: 't26', name: 'Denture Fitting' },
  },
  // Doctor 12 - Lazar Azoulay
  {
    id: '27',
    startTime: createDate(8, 30),
    endTime: createDate(9, 30),
    duration: 60,
    status: 'DONE',
    doctor: mockDoctors[11],
    patient: { id: 'p27', name: 'Umar Said' },
    treatment: { id: 't27', name: 'General Checkup' },
  },
  {
    id: '28',
    startTime: createDate(14, 0),
    endTime: createDate(15, 0),
    duration: 60,
    status: 'PENDING',
    doctor: mockDoctors[11],
    patient: { id: 'p28', name: 'Vera Susanti' },
    treatment: { id: 't28', name: 'Extraction' },
  },
];

// Break time configuration
export const BREAK_TIME = {
  start: 13,
  end: 14,
  label: 'BREAK TIME',
};

// UI-only design fixture for payment/visual state. Keep this sidecar out of
// Reservation so reservation data remains workflow/domain-shaped.
export const mockReservationVisualStates = {
  '1': 'unpaid',
  '2': 'paid',
  '3': 'inTreatment',
  '4': 'registered',
  '5': 'paid',
  '6': 'unpaid',
} as const;
